@host = localhost:4004
@protocol = https
@unsecureProtocol = http

GET {{unsecureProtocol}}://{{host}}/odata/v4/employee/getEmployeeByNumber(employeeNumber='EMP007')
Content-Type: application/json

GET {{unsecureProtocol}}://{{host}}/odata/v4/employee/Employees
Content-Type: application/json
# Authorization: Bearer {{access_token}}
# X-User-Id: {{userId}}



